on:
  pull_request:
    types: [opened]
name: Assign author to PR
jobs:
  assignAuthor:
    name: Auto assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
