name: Deploy Edge Application

on:
  push:
    branches:
      - main
      - workflow-fix

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: node:18-alpine3.18
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SO deps
        run: apk add curl git bash jq

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Download Azion CLI
        run: curl https://downloads.azion.com/linux/x86_64/azioncli -o azioncli && chmod +x azioncli

      - name: Configure Azion CLI
        run: ./azioncli configure -t ${{ secrets.PLATFORM_KIT_TOKEN }}

      - name: Define application settings
        run: >
            SETTINGS=$(jq
            --arg funcid ${{secrets.FUNCTION_ID}} 
            --arg appid ${{secrets.APPLICATION_ID}} 
            --arg domainid ${{secrets.DOMAIN_ID}} 
            '.function.id = ($funcid|tonumber)
            | .application.id = ($appid|tonumber)
            | .domain.id = ($domainid|tonumber)'
            azion/azion.json)

      - name: Save application settings
        run: echo $SETTINGS > azion/azion.json

      - name: Configure Repository
        run: mkdir -p .edge/statics && cp -r ./dist/* .edge/statics

      - name: Deploy Edge Application
        run: ./azioncli edge_applications publish --debug