name: Run Linters

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - dev
env:
  HUSKY: 0

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.18

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SO Dependencies
        run: apk add --no-cache curl bash git

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn ci

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier Formatting
        run: yarn format

      - name: Check for Uncommitted Changes
        run: |
          git config --global --add safe.directory $(pwd)
          if [[ -n $(git status --porcelain) ]]; then
            echo "‚ùå The code is not properly formatted. Run 'yarn format' locally and commit the changes before submitting the PR."
            exit 1
          fi
